// Template generated by myitcv.io/react/cmd/reactGen

package app

import (
	"github.com/gopherjs/gopherjs/es"
	"github.com/gopherjs/gopherjs/js"
	"honnef.co/go/js/console"
	"myitcv.io/react"
)

var styles = es.Import("./app.module.scss")
var reactIcon = es.Import("../assets/logo.svg")
var goIcon = es.Import("../assets/3b87e950352ac65c5eb643ddf9f2b21192138ae8.png")

type AppDef struct {
	react.ComponentDef
	Text string
}

type AppProps struct {
	react.Props
	Text string
}

func (props AppProps) EqualsIntf(v react.Props) bool {
	return false
}

type RRef struct {
	Name string
}

func (a AppDef) ComponentDidMount() {
	console.Error("测试error")
}

type clickEvent struct{}

func (context *clickEvent) OnClick(e *react.SyntheticMouseEvent) {
	js.Global.Call("open", "https://zh.m.wikipedia.org/zh/Go")
}

func (a AppDef) Render() react.Element {
	props := a.Props().(*AppProps)

	return react.Div(&react.DivProps{ClassName: styles("App")},
		react.Header(&react.HeaderProps{
			ClassName: styles("App-header"),
		},
			react.Img(&react.ImgProps{
				Src:       reactIcon(),
				ClassName: styles("App-logo"),
			}),
			react.P(nil,
				react.S("Edit "),
				react.Code(nil, react.S("src/app.x.go")),
				react.S(" and save to reload."),
			),
			react.A(
				&react.AProps{
					ClassName: styles("App-link"),
					Href:      "https://reactjs.org",
					Target:    "_blank",
				}),
			react.S(props.Text),
			react.Img(&react.ImgProps{
				ClassName: styles("App-go-logo"),
				Src:       goIcon(),
				OnClick:   &clickEvent{},
			}),
			react.Fragment(a.Children()...),
		),
	)
}
