// Template generated by myitcv.io/react/cmd/reactGen

package main

import (
	_ "github.com/jinzhu/copier"
	"github.com/zq2820/helloworld/src/app"
	"github.com/zq2820/helloworld/src/fun"
	"honnef.co/go/js/dom"
	"myitcv.io/react"
)

//go:generate gobin -m -run myitcv.io/react/cmd/reactGen

var document = dom.GetWindow().Document()

func main() {
	domTarget := document.GetElementByID("app")

	react.Render(
		react.CreateElement(
			&app.AppDef{},
			&app.AppProps{Text: "Learn Go React"},
			react.CreateElement(
				&fun.FunDef{},
				&fun.FunProps{Text: "FC"},
			),
		), domTarget)
}
